#!/usr/bin/env python3
# Copyright (C) 2026 Regalia
#
# AI-GEN: AI assisted
# This code was AI-assisted and has been reviewed for AGPL v3 compliance.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""Build chess.html from source modules - merges all .js files from chess.src/ into index.html.tpl

Exit codes:
  1 - template/module/output file I/O failure
  2 - __MODULE_SCRIPTS__ placeholder missing or duplicated in the template
  3 - a module still contains an 'export' statement after stripping
  4 - a module contains '</script' (would close the inline <script> early)
  5 - template header anchor (leading <!-- ... --> block) not found at the
      start of the assembled output; the AGPL v3 combined-work header could
      not be injected, so the build hard-aborts instead of shipping chess.html
      mislabeled with the template's GPL v3 header
"""
import os, re, sys

SRC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "main", "assets", "chess.src")
TPL = os.path.join(SRC_DIR, "index.html.tpl")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "main", "assets", "chess.html")

# v1.2.3 round-50 (report-headers §1): chess.html is a COMBINED WORK — the
#   GPL v3 template inlined with GPL v3 AND AGPL v3 modules (chess960.js,
#   eco-data.js, state-store.js) — so the generated file as a whole is
#   licensed under AGPL v3. The template keeps its own GPL v3 header (the
#   .tpl is not modified); the header below replaces the inherited tpl header
#   block in the generated output only.
NEW_HEADER = """<!--
  Copyright (C) 2026 Regalia

  This file is a COMBINED WORK generated by build-chess.py: the
  chess.src/index.html.tpl template (GPL v3) inlined with the
  chess.src/*.js modules (GPL v3 and AGPL v3 — see
  chess.src/README.license for the per-module classification).
  Because the bundle contains AGPL v3 modules (chess960.js,
  eco-data.js, state-store.js), the combined work as a whole is
  licensed under AGPL v3 (round-42 42-5, D2=A). The per-module
  license headers are preserved inline in the <script> block below.

  AI-GEN: AI assisted
  This code was AI-assisted and has been reviewed for AGPL v3 compliance.

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program. If not, see <https://www.gnu.org/licenses/>.
-->"""


def main():
    # v1.1.2 Phase 67 (MED-3): wrap all file I/O in try/except for clearer build diagnostics.
    try:
        with open(TPL, 'r', encoding='utf-8') as f:
            template = f.read()
    except FileNotFoundError:
        print(f"ERROR: template not found: {TPL}", file=sys.stderr)
        sys.exit(1)
    except OSError as e:
        print(f"ERROR: cannot read template {TPL}: {e}", file=sys.stderr)
        sys.exit(1)

    # Build the combined JS - order matters!
    # v1.2.1 (round-4 cleanup): Removed ui-audio.js, ui-board.js, ui-review.js,
    #   ui-toolbar.js — these were Phase-74 extracts that duplicated inline logic
    #   in ui.js / ai-bridge.js with subtly different conventions (rank order,
    #   move classification, audio state). They were never on the hot path and
    #   keeping them created two sources of truth.
    modules = [
        "game-logic.js",
        "chess960.js",
        "pgn-standard.js",
        "worker-pool.js",
        "state-store.js",      # v1.2.0 Phase 75: global state store (must be before ui.js)
        "ai-bridge.js",
        "tablebase.js",
        "eco-data.js",
        # v1.2.3 (God Class round-17): ui.js split — interaction handlers and
        #   game-flow/clock logic extracted into two global-scope modules.
        #   Concatenation order is safe: all extracted units are pure function
        #   declarations (hoisted bundle-wide); no top-level executable code
        #   was moved, so no TDZ/load-order change.
        "ui-gameflow.js",      # v1.2.3: game start + game-clock subsystem
        "ui-interactions.js",  # v1.2.3: clicks, move exec, toolbar, dialogs, back-press
        "ui.js",               # main UI (inline ChessAudioEngine + board rendering)
    ]

    js_parts = []
    for mod in modules:
        path = os.path.join(SRC_DIR, mod)
        try:
            with open(path, 'r', encoding='utf-8') as f:
                content = f.read()
        except FileNotFoundError:
            print(f"ERROR: module not found: {path}", file=sys.stderr)
            sys.exit(1)
        except OSError as e:
            print(f"ERROR: cannot read module {path}: {e}", file=sys.stderr)
            sys.exit(1)
        # Strip export statements (not needed in bundled file)
        content = re.sub(r'^export\s*\{[^}]*\}\s*;?\s*$', '', content, flags=re.MULTILINE)
        content = re.sub(r'^export\s+default\s+.*$', '', content, flags=re.MULTILINE)
        # v1.2.3 round-41: fail the build if any `export ` survived stripping
        #   (e.g. a new export form the regexes above don't cover). A leftover
        #   export in the bundled inline <script> is a runtime SyntaxError.
        if re.search(r'^\s*export\s', content, flags=re.MULTILINE):
            print(f"ERROR: residual 'export' statement in module {mod} after stripping", file=sys.stderr)
            sys.exit(3)
        # v1.2.3 round-49 (R5-8): fail the build if a module contains
        #   "</script" — the module source is inlined verbatim into the
        #   template's <script> block, and a literal "</script" would close
        #   it early (HTML injection / script truncation).
        if '</script' in content.lower():
            print(f"ERROR: module {mod} contains '</script' — would prematurely close the inline <script> block", file=sys.stderr)
            sys.exit(4)
        js_parts.append(content)

    combined_js = "\n".join(js_parts)

    # Replace ONLY the exact placeholder (not partial matches in JS code)
    placeholder = "/* __MODULE_SCRIPTS__ */"
    # v1.2.3 round-41: require EXACTLY ONE placeholder occurrence. A second
    #   copy would survive replace(..., 1) as a stale marker in the output;
    #   zero copies means the template is broken. Both are build errors.
    ph_count = template.count(placeholder)
    if ph_count != 1:
        print(f"ERROR: placeholder {placeholder!r} found {ph_count} time(s) in template {TPL} (expected exactly 1)", file=sys.stderr)
        sys.exit(2)
    result = template.replace(placeholder, combined_js, 1)

    # v1.2.3 round-50 (report-headers §1): swap the tpl's GPL v3 header block
    #   (the leading <!-- ... --> comment inherited at the very start of the
    #   assembled output) for the AGPL v3 combined-work header (NEW_HEADER).
    #   The anchor is extracted from the template itself, so the replacement
    #   is deterministic (same template -> same output, byte-for-byte). If the
    #   anchor is missing the build hard-aborts with exit 5 (see docstring).
    tpl_header_match = re.match(r'<!--.*?-->', template, flags=re.DOTALL)
    tpl_header = tpl_header_match.group(0) if tpl_header_match else None
    if tpl_header is None or not result.startswith(tpl_header):
        print(f"ERROR: template header anchor (leading <!-- ... --> block of {TPL}) not found at start of assembled output; refusing to write chess.html without the AGPL v3 combined-work header", file=sys.stderr)
        sys.exit(5)
    result = NEW_HEADER + result[len(tpl_header):]

    # v1.2.3 round-41: atomic write — write to a temp file in the same
    #   directory and os.replace() it into place, so an interrupted build
    #   never leaves a truncated chess.html.
    tmp_out = OUT + ".tmp"
    try:
        with open(tmp_out, 'w', encoding='utf-8') as f:
            f.write(result)
        os.replace(tmp_out, OUT)
    except OSError as e:
        print(f"ERROR: cannot write output {OUT}: {e}", file=sys.stderr)
        try:
            if os.path.exists(tmp_out):
                os.remove(tmp_out)
        except OSError:
            pass
        sys.exit(1)

    line_count = result.count('\n') + 1
    byte_count = len(result.encode('utf-8'))
    print(f"Built chess.html ({line_count} lines, {byte_count} bytes)")

    # v1.2.3 round-13 (P2): removed the stats.html CSP sha256 hash auto-update
    #   block. As of stats.html v1.1.2 PHASE 71, the CSP switched from a fixed
    #   sha256- hash to 'unsafe-inline' (stats.html line ~41: script-src
    #   'unsafe-inline' blob:). The regex `csp_pattern` never matched, so the
    #   block was silent dead code providing no protection. If a future policy
    #   reverts to hash-based CSP, the block can be re-added at that time.


if __name__ == '__main__':
    main()

