package com.Regalia;

/*
 * Regalia - Main Activity
 * Copyright (C) 2026 Regalia
 *
 * AI-GEN: AI assisted
 * This code was AI-assisted and has been reviewed for AGPL v3 compliance.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.res.Configuration;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.util.Log;
import android.view.Gravity;
import android.view.KeyEvent;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.widget.LinearLayout;
import android.widget.TextView;

/**
 * Regalia MainActivity - WebView-based chess game with Stockfish engine.
 *
 * Compatibility: Supports Android 6.0 (API 23) through Android 15 (API 35).
 * Android 15+ (API 35) Edge-to-Edge enforcement is handled via enableImmersiveMode().
 *
 * v18.4.1 CRITICAL FIX: Added robust crash protection:
 * - Wrapped entire onCreate in try-catch to prevent hard crash (闪退)
 * - AndroidX immersive mode uses reflection fallback if classes are missing
 * - All exception handlers log to logcat for debugging
 *
 * Version: v1.2.3
 */
public class MainActivity extends Activity {

    private static final String TAG = "Regalia";
    // v1.2.1 round-10 (review-E P3): Derive from BuildConfig.VERSION_NAME so the
    //   title ("Regalia v1.2.3") stays in sync with build.gradle's versionName
    //   without manual edits. BuildConfig is auto-generated by AGP in this
    //   package (com.Regalia) since build.gradle has buildConfig true.
    private static final String VERSION = "v" + BuildConfig.VERSION_NAME;

    // v1.2.3 round-44 (B6): theme colors as constants (were 4 x
    //   Color.parseColor literals — re-parsed on every fallback-UI build).
    private static final int COLOR_BG = 0xFF1A0A0A;
    private static final int COLOR_GOLD = 0xFFFFD700;
    private static final int COLOR_CREAM = 0xFFF5E6C8;

    // v1.2.3 round-49 (ROB-1): minimum Chromium major the bundled JS runs on.
    //   Parse floor is 80 (optional chaining `?.` x325 / `??` x21 across
    //   chess.src — below that the inlined <script> fails to parse at all).
    //   Raised to 84 because game-logic.js:1364 calls
    //   Element.getAnimations() (Chromium 84+) with only a try/catch, NOT a
    //   feature guard (no `typeof el.getAnimations==='function'` check), so
    //   80-83 would throw a runtime TypeError in the board-animation path.
    //   (Known residual, documented in round-49 fix notes: stats.html uses
    //   String.prototype.replaceAll — Chromium 85+ — unguarded in its SAN
    //   parser; a Chromium-84 WebView passes this gate but its stats page is
    //   still broken. Follow-up: replace those two replaceAll calls with
    //   regex .replace, or raise this gate to 85.)
    static final int MIN_SUPPORTED_CHROME_MAJOR = 84;

    // v1.2.3 round-44 (B5): volatile — written on the main thread (onCreate/
    //   showFallbackUI/onDestroy) and read via getWebView() from
    //   StockfishNative's engine/JS-binder threads.
    private volatile WebView webView;
    private StockfishNative stockfishEngine;
    private volatile boolean engineInitialized = false;
    private Handler initRetryHandler;
    private static final int INIT_RETRY_DELAY_MS = 5000; // 5 seconds
    private static final int INIT_MAX_RETRIES = 3;
    private int initRetryCount = 0;
    // OPT: P0 - Track if Activity is destroyed to prevent post-delayed callbacks from executing
    private volatile boolean isDestroyed = false;
    // v1.0.5 Round-6 Rev49: Sensor-based board anti-shake helper.
    // v1.2.3 round-13 (P3): corrected stale comment — helper is NOT recreated
    //   on each start(); it's created once on first toggle and reused. State
    //   reset is handled internally by StabilizationHelper.start().
    // v1.2.3 round-30 (robustness): declared `volatile` — both fields are
    //   read/written from the JS binder thread (via StockfishNative.toggle-
    //   Stabilization @JavascriptInterface entry point) AND from the main
    //   thread (onResume/onPause/onDestroy). Without volatile, the main
    //   thread may see a stale `false` after the user toggled stabilization
    //   on from JS, causing onResume to skip sensor restart.
    // v1.2.3 round-31 (PR52 CodeRabbit stability): volatile alone is not
    //   enough — the check-then-act pattern in toggleStabilization() (read
    //   stabilizationEnabled, then act) races with onDestroy() (set null,
    //   set false). Added _stabilizationLock to serialize toggle vs destroy
    //   and _destroyed guard to short-circuit post-destroy toggles. The
    //   fields stay volatile for the onResume/onPause single-reads.
    private volatile StabilizationHelper stabilizationHelper = null;
    private volatile boolean stabilizationEnabled = false;
    // v1.2.3 round-31: lock object for toggleStabilization() ↔ onDestroy()
    //   serialization. Fine-grained (not `this`) so unrelated main-thread
    //   entry points aren't blocked by a long sensor unregister.
    private final Object _stabilizationLock = new Object();
    // v1.2.3 round-31: tracks whether showFallbackUI() has been called and
    //   replaced the WebView content view. When true, BACK must NOT be
    //   dispatched to the (now-detached) WebView — it should fall through to
    //   super.onKeyDown() so the system finishes the Activity. Previously
    //   BACK was always dispatched to webView if webView!=null, which trapped
    //   the user in fallback mode (webView was still alive but invisible).
    private volatile boolean _isFallbackMode = false;

    // v1.2.3 round-48 (BUG-2): the manifest opts into
    //   android:enableOnBackInvokedCallback="true" — per AOSP lint
    //   GestureBackNavigation, that suppresses KeyEvent.KEYCODE_BACK dispatch
    //   on API 33+, so without a registered OnBackInvokedCallback the system
    //   would just finish the Activity and the whole JS back-handling chain
    //   (handleBackPress dialog priority etc.) would be bypassed. Register a
    //   PLATFORM android.window callback (no androidx dependency — the project
    //   has none) at PRIORITY_DEFAULT; API <= 32 keeps using onKeyDown().
    //   Unregistered in onDestroy().
    private android.window.OnBackInvokedCallback _backInvokedCallback = null;

    // v1.2.3 round-49 (review-4 P3-3): BACK ack fallback, ported from
    //   StatsActivity (round-44 E4 / round-46 CR#26). evaluateJavascript only
    //   QUEUES the script — a hung renderer never throws and never runs the
    //   ack, so without a timeout the user would be trapped by the
    //   unconditional `return true` below. The JS wrapper acks via
    //   AndroidBridge.ackMainBackHandled() from a `finally` whenever
    //   handleBackPress actually ran (any branch, including its intentional
    //   no-op tail — so the current "BACK with nothing open = no-op" UX is
    //   preserved). No ack within BACK_FALLBACK_MS → renderer presumed hung →
    //   finish(). Also: when handleBackPress is undefined (page broken /
    //   still loading), no ack is sent and the fallback finishes — a broken
    //   page must not trap the user either.
    private final java.util.concurrent.atomic.AtomicBoolean backCloseHandled =
            new java.util.concurrent.atomic.AtomicBoolean(false);
    private Handler backFallbackHandler;
    private static final int BACK_FALLBACK_MS = 250; // same as StatsActivity

    /**
     * v1.2.3 round-49 (review-4 P3-3): called from
     *   StockfishNative.ackMainBackHandled() (JS binder thread) when the
     *   BACK-dispatch JS actually executed. Package-private — no new public
     *   API. AtomicBoolean is thread-safe, no main-thread hop needed.
     */
    void notifyBackHandled() {
        backCloseHandled.set(true);
    }

    /**
     * v1.2.3 round-48 (BUG-2): register the platform OnBackInvokedCallback on
     *   API 33+ (TIRAMISU). The callback body reuses handleBackKeyPress() — the
     *   exact same logic as the onKeyDown(KEYCODE_BACK) branch — and finishes
     *   the Activity when that logic declines to consume the press.
     */
    private void registerBackInvokedCallback() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            try {
                _backInvokedCallback = new android.window.OnBackInvokedCallback() {
                    @Override
                    public void onBackInvoked() {
                        if (!handleBackKeyPress()) {
                            finish();
                        }
                    }
                };
                getOnBackInvokedDispatcher().registerOnBackInvokedCallback(
                        android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT,
                        _backInvokedCallback);
            } catch (Throwable e) {
                Log.w(TAG, "OnBackInvokedCallback registration failed", e);
                _backInvokedCallback = null;
            }
        }
    }

    /**
     * v1.2.3 round-48 (BUG-2): core BACK handling, extracted from onKeyDown so
     *   the API 33+ OnBackInvokedCallback can reuse it verbatim.
     *   Returns true when the press was consumed (dispatched to the WebView);
     *   false means the caller must apply the system default
     *   (onKeyDown: super.onKeyDown → finish; onBackInvoked: finish()).
     */
    private boolean handleBackKeyPress() {
        // v1.2.3 round-31 (PR52 CodeRabbit stability): if showFallbackUI()
        //   replaced the content view, the WebView is hidden but still
        //   alive in memory — dispatching BACK to it would call a JS
        //   handler on an invisible page and trap the user. Route to
        //   the system default instead so the system finishes the Activity.
        //   The pre-round-31 `webView != null` check only covered the
        //   "WebView creation failed" path; the "WebView exists but
        //   fallback UI replaced it" path was missed.
        if (_isFallbackMode) {
            return false;
        }
        if (webView != null) {
            // v1.2.3 round-49 (review-4 P3-3): arm the ack flag BEFORE
            //   dispatching, then schedule the 250ms fallback (see field doc).
            backCloseHandled.set(false);
            try {
                webView.evaluateJavascript(
                    "if(typeof handleBackPress==='function'){try{handleBackPress();}finally{" +
                    "if(typeof AndroidBridge!=='undefined'&&AndroidBridge.ackMainBackHandled){" +
                    "try{AndroidBridge.ackMainBackHandled();}catch(e){}}}}",
                    null);
            } catch (Throwable e) {
                // v1.2.3 round-48 (ROB-5): the JS bridge is broken — do NOT
                //   swallow BACK (the old code returned true unconditionally,
                //   trapping the user). Return false so the caller applies the
                //   system default (finish), matching the _isFallbackMode and
                //   webView==null branches.
                Log.w(TAG, "evaluateJavascript for back key failed", e);
                return false;
            }
            // v1.2.3 round-49 (review-4 P3-3): hung-renderer fallback. The
            //   ack above only proves the JS RAN; if the renderer is hung the
            //   script never executes, no ack arrives, and we finish here.
            //   backCloseHandled is also left true-free when JS handled BACK
            //   by closing the app itself (exitApp → finish → isFinishing()).
            if (backFallbackHandler != null) {
                backFallbackHandler.postDelayed(new Runnable() {
                    @Override public void run() {
                        if (!backCloseHandled.get() && !isFinishing() && !isDestroyed) {
                            Log.w(TAG, "BACK fallback: no JS ack within " + BACK_FALLBACK_MS + "ms — finishing");
                            finish();
                        }
                    }
                }, BACK_FALLBACK_MS);
            }
            return true;
        }
        // v1.2.3 round-18 (bug fix): WebView creation failed (fallback
        //   error UI is showing) — do NOT consume BACK; let the system
        //   finish the activity so the user is not trapped.
        return false;
    }

    @SuppressLint("SetJavaScriptEnabled")
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // v1.2.3 round-48 (BUG-2): register BEFORE onCreateInternal so the
        //   callback is active even if internal init falls into the fallback
        //   UI (whose BACK must still finish the Activity).
        registerBackInvokedCallback();

        // v18.4.1 CRITICAL FIX: Wrap ENTIRE onCreate in try-catch to prevent hard crash.
        // Previously, any uncaught exception here would crash the app immediately (闪退).
        // Now, we catch everything and show a fallback UI with the error message.
        try {
            onCreateInternal();
        // round-47: 有意兜底，防止 Error 逃逸导致组件死亡（onCreate 全局防闪退兜底，必须兜住 Error 以展示降级 UI）
        } catch (Throwable e) {
            Log.e(TAG, "=== FATAL: onCreate crashed ===", e);
            try {
                showFallbackUI("\u5e94\u7528\u521d\u59cb\u5316\u5931\u8d25: " + e.getMessage());
            // round-47: 有意兜底，防止 Error 逃逸导致组件死亡（降级 UI 自身的最后兜底）
            } catch (Throwable e2) {
                Log.e(TAG, "Even fallback UI failed", e2);
            }
        }
    }

    private void onCreateInternal() {
        // v18.4.6 CRITICAL FIX: Removed FLAG_FULLSCREEN — it is DEPRECATED since API 30
        // and CONFLICTS with Android 15+ Edge-to-Edge enforcement (targetSdk=35).
        // On Xiaomi HyperOS 3, FLAG_FULLSCREEN + setDecorFitsSystemWindows(false) causes
        // the WebView viewport to be pushed off-screen, resulting in COMPLETE BLACK SCREEN.
        // Instead, we rely on immersive mode (enableImmersiveMode) which is the correct
        // approach for hiding system bars on Android 11+.
        try {
            requestWindowFeature(Window.FEATURE_NO_TITLE);
        } catch (Throwable e) {
            Log.w(TAG, "requestWindowFeature failed", e);
        }

        // v18.4.6: Do NOT set FLAG_FULLSCREEN on API 30+ — it conflicts with Edge-to-Edge.
        // On API 23-29, FLAG_FULLSCREEN is still valid and needed for true fullscreen.
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
            try {
                getWindow().setFlags(
                        WindowManager.LayoutParams.FLAG_FULLSCREEN,
                        WindowManager.LayoutParams.FLAG_FULLSCREEN
                );
            } catch (Throwable e) {
                Log.w(TAG, "setFlags failed", e);
            }
        }

        // Try to create WebView - most likely point of failure
        try {
            webView = new WebView(this);
            // v18.4.6: Set WebView background to match CSS --bg (#1a0a0a) immediately,
            // so the user never sees a white flash or blank screen while chess.html loads.
            // This is critical for perceived startup speed on slow devices.
            webView.setBackgroundColor(COLOR_BG); // v1.2.3 round-44 (B6)
            // SECURITY FIX (MobSF #5): Prevent tapjacking — reject touches delivered
            // while the window is obscured by another overlay. This blocks malicious
            // apps that draw a transparent overlay on top to hijack taps.
            webView.setFilterTouchesWhenObscured(true);
        } catch (Throwable e) {
            Log.e(TAG, "WebView creation failed", e);
            showFallbackUI("WebView\u4e0d\u53ef\u7528: " + e.getMessage());
            return;
        }

        try {
            setContentView(webView);
        } catch (Throwable e) {
            Log.e(TAG, "setContentView failed", e);
            showFallbackUI("\u754c\u9762\u521b\u5efa\u5931\u8d25: " + e.getMessage());
            return;
        }

        // Enable immersive mode
        enableImmersiveMode();

        // Keep screen on during gameplay
        try {
            getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        } catch (Throwable e) {
            Log.w(TAG, "FLAG_KEEP_SCREEN_ON failed", e);
        }

        // v1.0.1: SCREENSHOTS ALLOWED.
        // The previous build applied FLAG_SECURE (MobSF #6 defense) which blocked
        // screenshots and the recent-tasks thumbnail. Users requested the ability
        // to capture the board (e.g., to share a position), so FLAG_SECURE is no
        // longer applied. The remaining defenses (file:// disabled, JS interface
        // gated by @JavascriptInterface, tapjacking filter) remain in effect.

        // Configure WebView settings
        // SECURITY FIX (MobSF #1): Disabled file system access flags to prevent
        // script injection from accessing local resources. The app loads its UI
        // from file:///android_asset/ which is NOT affected by setAllowFileAccess
        // (assets/resources are always reachable). All local file I/O (PGN import,
        // settings export) is routed through the AndroidBridge Java interface using
        // SAF (Storage Access Framework), so JS does not need file:// or content://
        // access. Disabling these three flags closes the WebView file-access attack
        // surface flagged by MobSF (MainActivity.java:154).
        try {
            WebSettings webSettings = webView.getSettings();
            webSettings.setJavaScriptEnabled(true);
            webSettings.setDomStorageEnabled(true);
            webSettings.setAllowFileAccess(false);
            webSettings.setAllowContentAccess(false);
            webSettings.setMediaPlaybackRequiresUserGesture(false);
            webSettings.setBuiltInZoomControls(false);
            webSettings.setDisplayZoomControls(false);
            webSettings.setUseWideViewPort(true);
            webSettings.setLoadWithOverviewMode(true);
            webSettings.setSupportZoom(false);
            webSettings.setCacheMode(WebSettings.LOAD_DEFAULT);
            webSettings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);
            webSettings.setTextZoom(100);
            webSettings.setAllowFileAccessFromFileURLs(false);
            webSettings.setAllowUniversalAccessFromFileURLs(false);
            // v1.0.8 PHASE 29 (PDF best practice): Enable Safe Browsing on API 26+
            //   to protect against malicious web content (defense-in-depth, even
            //   though we only load local assets). Safe Browsing checks URLs
            //   against Google's malware/phishing allowlist before navigation.
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                try {
                    webSettings.setSafeBrowsingEnabled(true);
                } catch (Throwable e) {
                    Log.w(TAG, "setSafeBrowsingEnabled failed", e);
                }
            }
            // Disable WebView force-dark (Android 10+) to prevent OEM dark mode
            // from inverting our dark theme colors (causes black-on-black text)
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                try {
                    webSettings.setForceDark(WebSettings.FORCE_DARK_OFF);
                } catch (Throwable e) {
                    // v18.4.6: setForceDark is deprecated in API 33+ but still functional.
                    // On some OEM WebViews it may throw — catch silently.
                    Log.w(TAG, "setForceDark failed (may be deprecated)", e);
                }
                // v18.4.6 FIX: Try BOTH setForceDarkBehavior AND setForceDarkStrategy.
                // The API name changed between Android 13 betas and release.
                // Some OEM ROMs (Xiaomi HyperOS) use the beta name, others use release name.
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                    boolean strategySet = false;
                    // Try release API name first: setForceDarkStrategy
                    try {
                        java.lang.reflect.Method method = WebSettings.class.getMethod("setForceDarkStrategy", int.class);
                        method.invoke(webSettings, 0); // FORCE_DARK_ONLY_ON_WEB_THEME_SUPPORT = 0
                        strategySet = true;
                        Log.d(TAG, "setForceDarkStrategy(0) applied");
                    } catch (NoSuchMethodException e) {
                        Log.d(TAG, "setForceDarkStrategy not found, trying setForceDarkBehavior");
                    } catch (Throwable e) {
                        Log.w(TAG, "setForceDarkStrategy failed", e);
                    }
                    // Fallback: try beta API name: setForceDarkBehavior
                    if (!strategySet) {
                        try {
                            java.lang.reflect.Method method = WebSettings.class.getMethod("setForceDarkBehavior", int.class);
                            method.invoke(webSettings, 0);
                            strategySet = true;
                            Log.d(TAG, "setForceDarkBehavior(0) applied");
                        } catch (NoSuchMethodException e) {
                            Log.d(TAG, "Neither setForceDarkStrategy nor setForceDarkBehavior found — device may not support it");
                        } catch (Throwable e) {
                            Log.w(TAG, "setForceDarkBehavior failed", e);
                        }
                    }
                }
            }
        } catch (Throwable e) {
            Log.w(TAG, "WebSettings configuration error", e);
        }

        // Set WebViewClient - init engine directly when page loads
        webView.setWebViewClient(new ChessWebViewClient(this));

        // Set WebChromeClient
        webView.setWebChromeClient(new WebChromeClient());

        // v1.2.3 round-49 (ROB-1): WebView version gate BEFORE any loadUrl.
        //   The bundled JS uses optional chaining (`?.`, 325x) and nullish
        //   coalescing (`??`) which need Chromium 80+ just to PARSE — on an
        //   older WebView the whole inlined <script> dies at parse time, and
        //   because engine readiness is a Java-side state the init watchdog
        //   exits early (isEngineReady) without ever triggering the native
        //   fallback: permanent white screen. Below the gate, skip loadUrl
        //   and go straight to showFallbackUI with an actionable message.
        //   Threshold rationale: see MIN_SUPPORTED_CHROME_MAJOR below.
        int chromeMajor;
        try {
            chromeMajor = extractChromeMajorFromUA(webView.getSettings().getUserAgentString());
        } catch (Throwable e) {
            // UA unreadable — conservative: treat as too old, but log for diagnosis.
            Log.w(TAG, "WebView UA read failed — treating as too old", e);
            chromeMajor = -1;
        }
        if (chromeMajor < 0) {
            Log.w(TAG, "WebView UA missing/unparseable — treating as too old (conservative)");
        }
        if (chromeMajor < MIN_SUPPORTED_CHROME_MAJOR) {
            Log.w(TAG, "WebView too old: Chrome major=" + chromeMajor
                    + " < " + MIN_SUPPORTED_CHROME_MAJOR + " — showing fallback UI");
            showFallbackUI(webViewTooOldMessage());
            return;
        }

        // Initialize Stockfish engine
        try {
            // v1.2.3 round-44 (B10, KNOWN DESIGN DEBT): StockfishNative is
            //   constructed on the main thread. The constructor is lightweight
            //   (SharedPreferences read + Handler/manager instantiation — no
            //   engine process spawn; the engine starts async via initEngine()),
            //   so startup impact is small. A lazy/async-proxy refactor was
            //   evaluated and rejected as high-risk for this wave.
            stockfishEngine = new StockfishNative(this);
            // SECURITY (MobSF #2): WebView.addJavascriptInterface is inherently flagged by
            // MobSF because a compromised WebView could call arbitrary Java methods. We
            // mitigate this with defense-in-depth:
            //   1. WebView only loads trusted local content (file:///android_asset/chess.html).
            //      No remote URLs are ever loaded (verified in ChessWebViewClient).
            //   2. All 64+ exposed methods carry @JavascriptInterface (verified by grep).
            //      On API 17+ (our minSdk=23), only annotated methods are reachable from JS,
            //      closing the historic reflection-based JS interface exploit.
            //   3. JavaScript is enabled only AFTER the WebView client is configured, so
            //      no remote content can race the JS interface registration.
            //   4. setAllowFileAccess / setAllowContentAccess / setAllowFileAccessFromFileURLs
            //      / setAllowUniversalAccessFromFileURLs are all disabled (MobSF #1 fix).
            //   5. setFilterTouchesWhenObscured(true) blocks tapjacking (MobSF #5 fix).
            //   6. (Removed in v1.0.1) FLAG_SECURE was disabled to allow screenshots.
            // The interface is therefore safe to expose: a remote attacker cannot inject JS
            // (no remote loading), and a local attacker with file access cannot reach JS
            // (file:// disabled). The remaining residual risk is acceptable for an offline
            // chess app with no sensitive data.
            webView.addJavascriptInterface(stockfishEngine, "AndroidBridge");
        } catch (Throwable e) {
            Log.e(TAG, "StockfishNative initialization failed", e);
            stockfishEngine = null;
        }

        // Load the chess HTML
        try {
            webView.loadUrl("file:///android_asset/chess.html");
        } catch (Throwable e) {
            Log.e(TAG, "Failed to load chess.html", e);
            showFallbackUI("\u52a0\u8f7d\u68cb\u76d8\u9875\u9762\u5931\u8d25: " + e.getMessage());
        }

        // Setup delayed init retry as safety net — if onPageFinished fails to trigger
        // or engine init hangs, this will retry initialization
        initRetryHandler = new Handler(Looper.getMainLooper());
        // v1.2.3 round-49 (review-4 P3-3): handler for the BACK ack fallback.
        backFallbackHandler = new Handler(Looper.getMainLooper());
        scheduleInitRetry();
    }

    /**
     * Schedule a delayed retry of engine initialization.
     * This acts as a safety net in case onPageFinished doesn't fire
     * or the engine init thread hangs.
     */
    private void scheduleInitRetry() {
        // v1.2.3 round-46 (PR53 CR#22): never schedule engine-init retries
        //   while the fallback UI is showing — the WebView is gone, so a
        //   queued retry would NPE on webView (swallowed by its own catch)
        //   and could build a StockfishNative with no JS bridge attached.
        if (_isFallbackMode) {
            Log.d(TAG, "Init retry skipped - fallback UI is showing");
            return;
        }
        initRetryHandler.removeCallbacksAndMessages(null);
        // v18.3.0: Lambda eliminated for HyperOS 3 ART compatibility (invokedynamic issue)
        initRetryHandler.postDelayed(new Runnable() {
            public void run() {
                // OPT: P0 - Guard against callback executing after Activity is finishing or destroyed.
                // This prevents crashes when the user exits the app before the delayed callback fires.
                if (isFinishing() || isDestroyed) {
                    Log.d(TAG, "Init retry skipped - activity is finishing or destroyed");
                    return;
                }
                if (stockfishEngine == null) {
                    Log.w(TAG, "Retry " + (initRetryCount + 1) + ": stockfishEngine is null, attempting re-creation");
                    try {
                        stockfishEngine = new StockfishNative(MainActivity.this);
                        webView.addJavascriptInterface(stockfishEngine, "AndroidBridge");
                    } catch (Throwable e) {
                        Log.e(TAG, "Engine re-creation failed", e);
                    }
                    // v1.2.3 round-34 (PR52 v4 Gitar Changes Requested): if the
                    //   constructor persistently fails, stockfishEngine remains
                    //   null. The round-33 fallback branch
                    //   `else if (stockfishEngine == null && initRetryCount >= INIT_MAX_RETRIES)`
                    //   was UNREACHABLE because initRetryCount was only
                    //   incremented in the `stockfishEngine != null` branch
                    //   below — so it stayed at 0 forever and the fallback
                    //   never fired. Fix: increment initRetryCount HERE when
                    //   re-creation failed, and re-schedule so the retry loop
                    //   continues until INIT_MAX_RETRIES is exhausted.
                    if (stockfishEngine == null) {
                        if (initRetryCount < INIT_MAX_RETRIES) {
                            initRetryCount++;
                            Log.w(TAG, "Engine re-creation failed — retry " + initRetryCount + "/" + INIT_MAX_RETRIES);
                            scheduleInitRetry();
                            return;
                        }
                        // All retries exhausted with stockfishEngine still null.
                        Log.e(TAG, "stockfishEngine null after " + INIT_MAX_RETRIES + " recreation attempts — showing fallback UI");
                        showFallbackUI(getString(R.string.app_name) + ": \u5f15\u64ce\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7\u91cd\u542f\u5e94\u7528 / Engine load failed. Please restart the app.");
                        return;
                    }
                }
                if (stockfishEngine != null && !stockfishEngine.isEngineReady() && initRetryCount < INIT_MAX_RETRIES) {
                    initRetryCount++;
                    Log.i(TAG, "Delayed engine init retry " + initRetryCount + "/" + INIT_MAX_RETRIES);
                    initStockfishEngine();
                    // Also trigger JS-side init via evaluateJavascript as backup
                    try {
                        webView.evaluateJavascript(
                            "try{if(typeof AndroidBridge!=='undefined'&&AndroidBridge.initEngine){AndroidBridge.initEngine();}}catch(e){console.error('Delayed init error:',e);}",
                            null
                        );
                    } catch (Throwable e) {
                        Log.w(TAG, "JS delayed init call failed", e);
                    }
                    scheduleInitRetry();
                } else if (stockfishEngine != null && !stockfishEngine.isEngineReady()
                           && initRetryCount >= INIT_MAX_RETRIES) {
                    // v1.2.3 round-30 (feature): all retries exhausted and the
                    //   engine still isn't ready. Show the fallback UI so the
                    //   user gets feedback instead of an indefinite spinner.
                    //   Previously the retry loop silently stopped, leaving the
                    //   user with a non-functional engine and no error message.
                    Log.e(TAG, "All " + INIT_MAX_RETRIES + " init retries exhausted — showing fallback UI");
                    // v1.2.3 round-33 (PR52 v3 #4.2.10): bilingual message —
                    //   the rest of showFallbackUI's calls use Chinese (unicode
                    //   escapes) for consistency with the project convention,
                    //   but ChessWebViewClient.java uses bilingual format for
                    //   runtime fallback messages. This round-30 message was
                    //   English-only, breaking the convention. Now bilingual.
                    showFallbackUI(getString(R.string.app_name) + ": \u5f15\u64ce\u521d\u59cb\u5316\u5931\u8d25\uff0c\u8bf7\u91cd\u542f\u5e94\u7528 / Engine init failed. Please restart the app.");
                }
            }
        }, INIT_RETRY_DELAY_MS);
    }

    void initEngineAfterPermissions() {
        // FIX: null-safe check — if engineInitialized is true but stockfishEngine is null
        // (constructor failed), we must NOT throw NPE and should allow re-init attempts
        if (engineInitialized) {
            if (stockfishEngine != null && stockfishEngine.isEngineReady()) {
                Log.i(TAG, "Engine already ready, skipping init");
                return;
            }
            // Engine was marked initialized but not ready — reset flag to allow retry
            Log.w(TAG, "Engine init flag set but engine not ready, allowing retry");
            engineInitialized = false;
        }
        if (stockfishEngine == null) {
            Log.e(TAG, "Cannot init engine — stockfishEngine is null");
            return;
        }
        engineInitialized = true;
        initRetryCount = 0; // Reset retry count on successful init attempt
        Log.i(TAG, "Initializing engine");
        initStockfishEngine();
    }

    void initStockfishEngine() {
        if (stockfishEngine != null && !stockfishEngine.isEngineReady()) {
            try {
                stockfishEngine.initEngine();
            } catch (Exception e) {
                Log.e(TAG, "Engine init failed", e);
            }
        }
    }

    // v1.2.3 round-13 (P1): package-private (not private) so ChessWebViewClient
    //   can invoke it from the render-crash backoff path (4+ crashes in 60s)
    //   to show the user a recovery message instead of a frozen screen.
    void showFallbackUI(String message) {
        // v1.2.3 round-46 (PR53 CR#22): cancel pending engine-init retries
        //   FIRST — once the fallback UI replaces the WebView, a queued retry
        //   would dereference the destroyed/null webView (NPE swallowed by its
        //   own catch) and could construct a StockfishNative with no JS bridge.
        //   scheduleInitRetry() is additionally guarded by _isFallbackMode so
        //   retries not yet posted (e.g. the loadUrl-failure path below in
        //   onCreateInternal) are skipped as well.
        if (initRetryHandler != null) {
            initRetryHandler.removeCallbacksAndMessages(null);
        }
        // v1.2.3 round-44 (B3): destroy the old WebView before swapping in the
        //   fallback view — previously it stayed alive (hidden), pinning the
        //   engine JS bridge + native resources for the rest of the process
        //   lifetime. All `webView != null` call sites tolerate the null, and
        //   _isFallbackMode already gates BACK dispatch. Each step guarded so
        //   a half-broken WebView cannot block the fallback UI itself.
        final WebView oldWebView = webView;
        if (oldWebView != null) {
            try { oldWebView.stopLoading(); } catch (Throwable t) { Log.w(TAG, "fallback: stopLoading failed", t); }
            try { oldWebView.loadUrl("about:blank"); } catch (Throwable t) { Log.w(TAG, "fallback: about:blank failed", t); }
            try { oldWebView.removeJavascriptInterface("AndroidBridge"); } catch (Throwable t) { Log.w(TAG, "fallback: removeJavascriptInterface failed", t); }
            // v1.2.3 round-46 (PR53 CR#23): detach from the parent view BEFORE
            //   destroy() — Android requires a WebView to be removed from the
            //   view hierarchy first; destroying an attached WebView can throw
            //   or leak the window (same step order as runWebViewTeardown).
            try {
                if (oldWebView.getParent() instanceof android.view.ViewGroup) {
                    ((android.view.ViewGroup) oldWebView.getParent()).removeView(oldWebView);
                }
            } catch (Throwable t) { Log.w(TAG, "fallback: removeView failed", t); }
            try { oldWebView.destroy(); } catch (Throwable t) { Log.w(TAG, "fallback: destroy failed", t); }
            webView = null;
        }
        try {
            LinearLayout layout = new LinearLayout(this);
            layout.setOrientation(LinearLayout.VERTICAL);
            layout.setGravity(Gravity.CENTER);
            layout.setBackgroundColor(COLOR_BG); // v1.2.3 round-44 (B6)
            layout.setPadding(32, 32, 32, 32);

            TextView titleView = new TextView(this);
            titleView.setText("Regalia " + VERSION);
            titleView.setTextColor(COLOR_GOLD); // v1.2.3 round-44 (B6)
            titleView.setTextSize(24);
            titleView.setGravity(Gravity.CENTER);
            titleView.setPadding(0, 0, 0, 24);

            TextView msgView = new TextView(this);
            msgView.setText(message);
            msgView.setTextColor(COLOR_CREAM); // v1.2.3 round-44 (B6)
            msgView.setTextSize(16);
            msgView.setGravity(Gravity.CENTER);

            layout.addView(titleView);
            layout.addView(msgView);
            setContentView(layout);
            // v1.2.3 round-31 (PR52 CodeRabbit stability): mark fallback mode
            //   so onKeyDown(BACK) routes to super instead of the now-hidden
            //   WebView. setContentView replaces the WebView as the visible
            //   content but does NOT null out the webView field or destroy
            //   it — without this flag, BACK presses would still be forwarded
            //   to webView.evaluateJavascript("handleBackPress()"), trapping
            //   the user in the fallback screen.
            _isFallbackMode = true;
        } catch (Throwable e) {
            Log.e(TAG, "Fallback UI failed", e);
        }
    }

    /**
     * v1.2.3 round-49 (ROB-1): extract the Chromium major version from the
     *   WebView user-agent string ("Mozilla/5.0 ... Chrome/84.0.4147.89 ...").
     *   The UA is the most reliable cross-provider signal: both the
     *   Chrome-backed WebView and Android System WebView stamp "Chrome/<n>"
     *   into the default UA, whereas WebViewPackage.getVersionName() is
     *   API 26+ only and its package version does not always equal the
     *   Chromium major. Package-private static (no new public API) so
     *   StatsActivity applies the identical gate.
     *   @return the major version, or -1 when the UA is null/unparseable
     *           (callers treat -1 as "too old" — conservative — but log it).
     */
    static int extractChromeMajorFromUA(String ua) {
        if (ua == null || ua.isEmpty()) {
            return -1;
        }
        try {
            java.util.regex.Matcher m = java.util.regex.Pattern.compile("Chrome/(\\d+)").matcher(ua);
            if (m.find()) {
                return Integer.parseInt(m.group(1));
            }
        } catch (Throwable ignored) {}
        return -1;
    }

    // v1.2.3 round-49 (ROB-1): bilingual (zh + en, both concatenated) gate
    //   message — follows the existing showFallbackUI convention of hardcoded
    //   bilingual strings (see the engine-init-failure call above), NOT
    //   strings.xml. Also reused by StatsActivity's Toast fallback.
    static String webViewTooOldMessage() {
        return "系统WebView版本过旧，无法运行（需要 Chrome/Android System WebView ≥ "
                + MIN_SUPPORTED_CHROME_MAJOR
                + "）。请前往应用商店更新“Android System WebView”后重试。"
                + " The system WebView is too old (requires Chrome/Android System WebView ≥ "
                + MIN_SUPPORTED_CHROME_MAJOR
                + "). Please update \"Android System WebView\" from the app store and try again.";
    }
    /**
     * v18.4.6 CRITICAL FIX: Completely rewrote enableImmersiveMode().
     *
     * ROOT CAUSE of black screen: The previous implementation used AndroidX reflection
     * (WindowCompat.setDecorFitsSystemWindows) to set decorFitsSystemWindows=false.
     * On Android 15+ (targetSdk=35), Edge-to-Edge is MANDATORY — the system already
     * sets decorFitsSystemWindows=false automatically. Our explicit call was CONFLICTING
     * with the system's Edge-to-Edge enforcement, causing the WebView's viewport to
     * be offset incorrectly (content pushed behind the status bar or off-screen entirely).
     *
     * FIX: On Android 15+ (API 35), do NOT call setDecorFitsSystemWindows at all —
     * let the system handle Edge-to-Edge natively. On Android 11-14 (API 30-34),
     * use the platform WindowInsetsController API directly (no AndroidX reflection).
     * On Android 6-10, use legacy system UI visibility flags.
     *
     * This eliminates the AndroidX reflection chain that was causing ClassNotFoundException
     * and VerifyError on some devices, and removes the conflicting setDecorFitsSystemWindows
     * call that was causing black screens on Xiaomi HyperOS 3.
     */
    @SuppressLint("NewApi")
    private void enableImmersiveMode() {
        try {
            // On Android 15+ (API 35+), Edge-to-Edge is enforced by the system.
            // Do NOT call setDecorFitsSystemWindows — it conflicts with the system setting.
            // Only hide the system bars using the platform API.
            if (Build.VERSION.SDK_INT >= 35) {
                // Android 15+: Use platform WindowInsetsController to hide system bars
                try {
                    getWindow().getInsetsController().hide(android.view.WindowInsets.Type.systemBars());
                    getWindow().getInsetsController().setSystemBarsBehavior(
                            android.view.WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);
                    Log.d(TAG, "Android 15+ immersive mode: system bars hidden via platform API");
                } catch (Throwable e) {
                    Log.w(TAG, "Android 15+ insetsController failed, using legacy fallback", e);
                    applyLegacyImmersiveMode(getWindow().getDecorView());
                }
                return;
            }

            // Android 11-14 (API 30-34): Use platform WindowInsetsController
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                try {
                    getWindow().setDecorFitsSystemWindows(false);
                    getWindow().getInsetsController().hide(android.view.WindowInsets.Type.systemBars());
                    getWindow().getInsetsController().setSystemBarsBehavior(
                            android.view.WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);
                    Log.d(TAG, "Android 11-14 immersive mode applied via platform API");
                } catch (Throwable e) {
                    Log.w(TAG, "Platform insetsController failed, trying legacy", e);
                    try {
                        // Fallback: setDecorFitsSystemWindows + legacy flags
                        getWindow().setDecorFitsSystemWindows(false);
                    } catch (Throwable e2) {
                        Log.w(TAG, "setDecorFitsSystemWindows also failed", e2);
                    }
                    applyLegacyImmersiveMode(getWindow().getDecorView());
                }
                return;
            }

            // Android 6-10 (API 23-29): Legacy system ui visibility flags
            View decorView = getWindow().getDecorView();
            if (decorView != null) {
                applyLegacyImmersiveMode(decorView);
            }
        } catch (Throwable e) {
            Log.w(TAG, "enableImmersiveMode failed", e);
        }
    }

    /**
     * OPT: P0/P4 - Extracted legacy immersive mode logic for reuse and clarity.
     * Used on Android 6.x through Android 10 (API 23-29).
     */
    private void applyLegacyImmersiveMode(View decorView) {
        decorView.setSystemUiVisibility(
                View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
                        | View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                        | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                        | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                        | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                        | View.SYSTEM_UI_FLAG_FULLSCREEN
        );
    }

    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
        if (hasFocus) {
            enableImmersiveMode();
        }
    }

    /**
     * v18.5.0 FIX: Handle configuration changes (screen rotation) without Activity recreation.
     * Previously, android:screenOrientation="portrait" prevented rotation entirely.
     * Now with "unspecified", the Activity can rotate, and since configChanges includes
     * orientation|screenSize, the system calls this method instead of recreating the Activity.
     * We trigger a JS render() to update the CSS landscape/portrait layout.
     */
    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        int orientation = newConfig.orientation;
        Log.i(TAG, "Configuration changed: orientation=" +
                (orientation == Configuration.ORIENTATION_LANDSCAPE ? "landscape" :
                 orientation == Configuration.ORIENTATION_PORTRAIT ? "portrait" : "undefined"));
        // Re-apply immersive mode after rotation
        enableImmersiveMode();
        // Trigger JS-side re-render to apply landscape/portrait CSS rules
        if (webView != null) {
            try {
                webView.evaluateJavascript(
                    "try{if(typeof render==='function')render();}catch(e){console.error('render on config change failed:',e);}",
                    null
                );
            } catch (Throwable e) {
                Log.w(TAG, "Failed to trigger render on config change", e);
            }
        }
    }

    @Override
    public void onResume() {
        super.onResume();
        // v1.2.3 round-44 (B1/B7): new foreground episode — re-arm the flush dedup.
        flushedSinceResume = false;
        if (webView != null) {
            try {
                webView.onResume();
            } catch (Throwable e) {
                Log.w(TAG, "webView.onResume failed", e);
            }
        }
        enableImmersiveMode();

        // v1.0.5 Round-6 Rev49: Re-start sensor-based stabilization if it was
        //   enabled before pause (battery-saving stop in onPause).
        // v1.2.3 round-33 (PR52 v3 #4.1.4): synchronize on _stabilizationLock
        //   to close the race window — without the lock, the JS binder thread
        //   could call toggleStabilization() (which IS locked) concurrently
        //   with this read, causing us to see a stale stabilizationEnabled /
        //   stabilizationHelper pair. Round-31 added the lock for
        //   toggleStabilization + onDestroy but missed onResume/onPause; this
        //   round closes that gap. The lock is fine-grained (not `this`) so
        //   unrelated main-thread entry points aren't blocked.
        synchronized (_stabilizationLock) {
            if (isDestroyed) {
                // Activity is being destroyed — skip (matches onDestroy's
                // short-circuit in toggleStabilization).
            } else if (stabilizationEnabled && stabilizationHelper != null) {
                try { stabilizationHelper.start(); } catch (Exception e) { Log.w(TAG, "stab restart on resume failed", e); }
            }
        }

        // Retry engine init if not ready (handles case where init failed previously)
        // v1.0.8 PHASE 30: drop the !engineInitialized check — initEngineAfterPermissions sets
        //   engineInitialized=true even on failure, which blocked this retry path. The init
        //   method itself is idempotent (returns early if engineReady), so the guard is safe.
        if (stockfishEngine != null && !stockfishEngine.isEngineReady()) {
            Log.i(TAG, "onResume: engine not ready, retrying");
            initEngineAfterPermissions();
        }

        // v1.0.2 FEATURE: Handle pending review request from StatsActivity.
        if (pendingStatsReviewRequest) {
            // round-47 (S2696 kept): pendingStatsReviewRequest 为跨 Activity 一次性请求标记（StatsActivity 写、此处消费），有意保持 static。
            pendingStatsReviewRequest = false;
            // Enter review mode on the main WebView
            if (webView != null) {
                webView.evaluateJavascript("if(typeof onStatsRequestReview==='function')onStatsRequestReview()", null);
            }
        }

        // v1.0.4 Rev28: If the user imported a PGN on the stats page (via 🗃️
        // Paste PGN or 📂 Select PGN File) and then returned to the main
        // activity, prompt "🗃️ Import PGN to game?" Yes/No/Cancel.
        // The imported PGN text is stashed in StatsActivity.importedPGNOnStats
        // (a static volatile field) by the stats page's setImportedPGN() bridge
        // method. We read it here (one-shot — clear immediately so a subsequent
        // resume without a new import doesn't re-prompt).
        // The actual Yes/No/Cancel dialog is rendered in JS (see ui.js
        // showStatsImportBackPrompt) so it matches the app's dialog style.
        // Cancel = stay on stats page is NOT possible from here (we're already
        // back on MainActivity); Cancel in this context = dismiss the prompt
        // without importing. The "stay on stats" behavior is handled in
        // stats.html's returnToGame() interceptor.
        if (StatsActivity.importedPGNOnStats != null) {
            final String importedPGN = StatsActivity.importedPGNOnStats;
            // round-47 (S2696 kept): importedPGNOnStats 为跨 Activity 静态握手字段（StatsActivity 写入、此处读取后清零），有意为之。
            StatsActivity.importedPGNOnStats = null; // One-shot consume
            if (webView != null && importedPGN.length() > 0) {
                // JSON-encode the PGN text for safe JS string passing.
                String jsonPGN;
                try {
                    jsonPGN = new org.json.JSONObject().put("pgn", importedPGN).toString();
                } catch (Throwable je) {
                    Log.e(TAG, "JSON encoding failed for stats import-back PGN", je);
                    jsonPGN = "{\"pgn\":\"\"}";
                }
                webView.evaluateJavascript(
                    "if(typeof _showStatsImportBackPrompt==='function'){try{var _d=" + jsonPGN +
                    ";_showStatsImportBackPrompt(_d.pgn);}catch(e){console.error('stats import-back prompt error:',e);}}",
                    null);
            }
        }
    }

    // v1.0.2 FEATURE: Static flag for cross-activity communication with StatsActivity
    public static volatile boolean pendingStatsReviewRequest = false;

    // v1.2.3 round-44 (B1/B7): dedup flag — at most one flush per
    //   backgrounding episode (pause->stop->destroy chains would otherwise
    //   flush 3x). Reset in onResume. onDestroy bypasses the dedup via
    //   force=true so the FINAL flush is never skipped.
    private volatile boolean flushedSinceResume = false;

    /**
     * v1.2.3 round-44 (B1/B7): unified lifecycle state flush, delegating target
     *   for onPause/onStop/onUserLeaveHint/onDestroy. Order: JS first
     *   (_flushReviewEvalCache writes eval_cache.json synchronously via the
     *   bridge), then SharedPreferences pending writes (persistentFlush).
     *
     * @param reason caller tag for logging
     * @param force  when true (onDestroy only), flush even if already flushed
     *               since resume — the destroy flush is the last chance before
     *               process death and must not be deduped away.
     */
    private void flushAllState(String reason, boolean force) {
        if (!force && flushedSinceResume) {
            Log.d(TAG, "flushAllState(" + reason + ") skipped — already flushed since resume");
            return;
        }
        flushedSinceResume = true;
        if (webView != null) {
            try {
                webView.evaluateJavascript("try{if(typeof _flushReviewEvalCache==='function')_flushReviewEvalCache();}catch(e){}", null);
            } catch (Throwable ignored) {}
        }
        if (stockfishEngine != null) {
            try {
                stockfishEngine.persistentFlush();
            } catch (Exception e) {
                Log.w(TAG, "persistentFlush failed (" + reason + ")", e);
            }
        }
    }

    private void flushAllState(String reason) {
        flushAllState(reason, false);
    }

    @Override
    public void onPause() {
        super.onPause();
        // v1.0.5 Round-6 Rev49: Stop sensor-based stabilization when backgrounded
        //   (battery saving). onResume will restart it IF it was enabled.
        // v1.2.3 round-33 (PR52 v3 #4.1.4): synchronize on _stabilizationLock
        //   to close the race window (see onResume comment for rationale).
        synchronized (_stabilizationLock) {
            if (stabilizationEnabled && stabilizationHelper != null) {
                try { stabilizationHelper.stop(); } catch (Exception e) { Log.w(TAG, "stab stop on pause failed", e); }
            }
        }
        // v1.2.3 round-44 (B1/B7): unified flush entry (Rev20 rationale:
        //   HyperOS 3 kills backgrounded apps aggressively; without this flush
        //   any writes queued by persistentSet()'s async apply() would be lost).
        flushAllState("pause");
        if (webView != null) {
            try {
                webView.onPause();
            } catch (Throwable e) {
                Log.w(TAG, "webView.onPause failed", e);
            }
        }
    }

    @Override
    public void onStop() {
        super.onStop();
        // v1.2.3 round-44 (B1/B7): onStop may be the last callback before a
        //   HyperOS SIGKILL — flush (deduped against the onPause flush).
        flushAllState("stop");
    }

    @Override
    public void onUserLeaveHint() {
        super.onUserLeaveHint();
        // v1.2.3 round-44 (B1/B7): User pressed Home — same risk as onPause/onStop.
        flushAllState("userLeaveHint");
    }

    @Override
    public void onDestroy() {
        // OPT: P0 - Set destroyed flag first so delayed callbacks check it before executing.
        isDestroyed = true;

        // v1.2.3 round-48 (BUG-2): unregister the API 33+ back callback so the
        //   dispatcher cannot invoke a destroyed Activity.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU && _backInvokedCallback != null) {
            try {
                getOnBackInvokedDispatcher().unregisterOnBackInvokedCallback(_backInvokedCallback);
            } catch (Throwable e) {
                Log.w(TAG, "OnBackInvokedCallback unregister failed", e);
            }
            _backInvokedCallback = null;
        }

        // v1.0.5 Round-6 Rev49: Stop sensor-based stabilization and release sensors.
        // v1.2.3 round-31 (PR52 CodeRabbit stability): acquire _stabilizationLock
        //   so toggleStabilization() on the JS binder thread can't be mid-flight
        //   (creating/starting a helper) while we null out the field. The lock
        //   is fine-grained; sensor unregister is fast (~ms).
        synchronized (_stabilizationLock) {
            if (stabilizationHelper != null) {
                try { stabilizationHelper.stop(); } catch (Exception e) { Log.w(TAG, "stab stop on destroy failed", e); }
                stabilizationHelper = null;
            }
            stabilizationEnabled = false;
        }

        // OPT: P0 - Cancel any pending init retry callbacks and release Handler reference
        // to prevent memory leaks and late callback execution.
        if (initRetryHandler != null) {
            initRetryHandler.removeCallbacksAndMessages(null);
            initRetryHandler = null;
        }
        // v1.2.3 round-49 (review-4 P3-3): same for the BACK ack fallback handler.
        if (backFallbackHandler != null) {
            backFallbackHandler.removeCallbacksAndMessages(null);
            backFallbackHandler = null;
        }
        // v1.2.3 round-44 (B1/B7): final flush — FORCED (ignores the dedup
        //   flag): onDestroy may be the last callback before process death and
        //   any eval data that arrived since the onStop flush must hit disk
        //   (Rev22 rationale: JS eval-cache first, then SharedPreferences —
        //   that order now lives in flushAllState).
        flushAllState("destroy", true);
        // Notify JS to clean up event listeners and timers before destroying
        // the WebView. v1.2.3 round-44 (B2): the teardown is CHAINED to this
        //   evaluateJavascript's value callback so the JS cleanup (and the
        //   flush above) actually execute before native destroy; a 500ms
        //   postDelayed fallback forces teardown if the renderer is frozen and
        //   the callback never fires. runWebViewTeardown is idempotent
        //   (AtomicBoolean guard), so both paths may fire safely.
        final WebView wvToTeardown = webView;
        if (wvToTeardown != null) {
            try {
                wvToTeardown.evaluateJavascript(
                    "try{if(typeof _cleanupEventListeners==='function')_cleanupEventListeners();}catch(e){}",
                    new android.webkit.ValueCallback<String>() {
                        @Override public void onReceiveValue(String value) {
                            runWebViewTeardown(wvToTeardown);
                        }
                    });
            } catch (Throwable e) {
                Log.w(TAG, "onDestroy JS cleanup eval failed", e);
            }
            new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
                public void run() {
                    runWebViewTeardown(wvToTeardown);
                }
            }, 500);
        }
        if (stockfishEngine != null) {
            try {
                stockfishEngine.shutdown();
            } catch (Exception e) {
                Log.w(TAG, "Engine shutdown failed", e);
            }
        }
        super.onDestroy();
    }

    // v1.2.3 round-44 (B2): one-shot guard — teardown runs from the JS cleanup
    //   callback OR the timed fallback, whichever fires first.
    // v1.2.3 round-46 (PR53 CR#24): fallback raised 100ms -> 500ms — under load
    //   the JS cleanup callback can legitimately take >100ms to arrive, and the
    //   100ms fallback fired early, skipping the JS-side listener cleanup.
    private final java.util.concurrent.atomic.AtomicBoolean _webViewTeardownDone =
            new java.util.concurrent.atomic.AtomicBoolean(false);

    /**
     * v1.2.3 round-44 (B2): full WebView teardown, extracted from onDestroy so
     *   it can be chained to the JS cleanup callback with a timed fallback.
     *   Idempotent via _webViewTeardownDone. Step order preserved from the
     *   v1.0.8 PHASE 29 / v1.1.2 Phase 67 sequence: stopLoading (abort in-flight
     *   loads — SIGSEGV guard on HyperOS/MIUI) -> removeView (WindowLeaked) ->
     *   clearHistory -> about:blank (drop JS callbacks/document) ->
     *   removeJavascriptInterface (stale AndroidBridge) -> onPause (JS
     *   timers/media) -> destroy (native teardown). Each step individually
     *   guarded — a half-destroyed WebView must not block the rest.
     */
    private void runWebViewTeardown(final WebView wv) {
        if (wv == null) return;
        if (!_webViewTeardownDone.compareAndSet(false, true)) return;
        try {
            wv.stopLoading();
        } catch (Throwable e) {
            Log.w(TAG, "WebView stopLoading failed", e);
        }
        try {
            if (wv.getParent() instanceof android.view.ViewGroup) {
                ((android.view.ViewGroup) wv.getParent()).removeView(wv);
            }
        } catch (Throwable e) {
            Log.w(TAG, "WebView removeView failed", e);
        }
        try {
            wv.clearHistory();
        } catch (Throwable e) {
            Log.w(TAG, "WebView clearHistory failed", e);
        }
        try {
            wv.loadUrl("about:blank");
        } catch (Throwable e) {
            Log.w(TAG, "WebView loadUrl about:blank failed", e);
        }
        try {
            wv.removeJavascriptInterface("AndroidBridge");
        } catch (Throwable e) {
            Log.w(TAG, "WebView removeJavascriptInterface failed", e);
        }
        try {
            wv.onPause();
        } catch (Throwable e) {
            Log.w(TAG, "WebView onPause failed", e);
        }
        try {
            wv.destroy();
        } catch (Throwable e) {
            Log.w(TAG, "WebView destroy failed", e);
        }
        webView = null;
    }

    // v1.2.3 round-44 (B9): persist lightweight Activity state. LIMITATION:
    //   the live FEN exists only inside the WebView JS context and cannot be
    //   read synchronously here (evaluateJavascript is async and the page may
    //   already be suspending), so we persist only flags + force a durability
    //   flush of the SharedPreferences-backed store; game-state restoration
    //   relies on the JS layer's own persistence (review/eval cache, PGN).
    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        try {
            outState.putBoolean("engineInitialized", engineInitialized);
            outState.putBoolean("fallbackMode", _isFallbackMode);
            flushAllState("saveInstanceState");
        } catch (Throwable e) {
            Log.w(TAG, "onSaveInstanceState failed", e);
        }
    }

    // v1.2.3 round-44 (B9): on moderate+ memory pressure, make our own state
    //   durable. LIMITATION: StockfishNative exposes no partial memory-release
    //   interface (UCI has no mid-game-safe "shrink hash"; a full shutdown
    //   would forfeit the game), so there is no engine-side release hook to
    //   call — engine RAM is reclaimed by the OS only via process kill, after
    //   which the heartbeat's recoverEngine() restarts it.
    @Override
    public void onTrimMemory(int level) {
        super.onTrimMemory(level);
        if (level >= TRIM_MEMORY_MODERATE) {
            try {
                flushAllState("trimMemory");
            } catch (Exception e) {
                Log.w(TAG, "onTrimMemory flush failed", e);
            }
        }
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK) {
            // v1.2.3 round-48 (BUG-2/ROB-5): logic extracted to
            //   handleBackKeyPress() (shared with the API 33+
            //   OnBackInvokedCallback — on API 33+ this onKeyDown branch no
            //   longer receives KEYCODE_BACK at all). A false return
            //   (fallback mode / WebView gone / evaluateJavascript threw)
            //   routes to super so the system finishes the Activity.
            if (handleBackKeyPress()) {
                return true;
            }
            return super.onKeyDown(keyCode, event);
        }
        return super.onKeyDown(keyCode, event);
    }

    /**
     * FIX: Handle SAF file picker results for settings import and export.
     * - REQUEST_CODE_IMPORT_SETTINGS: Reads the selected file via ContentResolver and imports settings.
     * - REQUEST_CODE_EXPORT_SETTINGS: Writes pending export content to the user-chosen location.
     */
    @Override
    protected void onActivityResult(int requestCode, int resultCode, android.content.Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        // v1.0.8 PHASE 24 (bug fix): On user-cancel (resultCode != RESULT_OK),
        //   clear pending export content and notify JS so "Exporting..." dialogs
        //   don't hang forever. Previously the early return left stale state.
        if (resultCode != RESULT_OK) {
            try {
                if (stockfishEngine != null && (requestCode == StockfishNative.REQUEST_CODE_EXPORT_SETTINGS
                        || requestCode == StockfishNative.REQUEST_CODE_EXPORT_PGN)) {
                    stockfishEngine.cancelPendingExport();
                }
            } catch (Exception ignored) {}
            // v1.2.3 round-49 (BUG-19): symmetry with the export-cancel path
            //   above — the two IMPORT pickers previously returned silently.
            //   Notify JS via the typeof-guarded onImportCancelled hook. The
            //   hook is currently log-only: both import chains open the SAF
            //   picker without setting any pending/"importing" state
            //   (verified round-49: importPGNFile → AndroidBridge.openPGNFilePicker,
            //   importEngineSettings → bridge.openSystemFilePicker), so there
            //   is nothing to clear — this just completes the notification
            //   symmetry and leaves a diagnostic trace. Fired even when
            //   stockfishEngine is null (the JS side does not depend on it).
            if (webView != null && (requestCode == StockfishNative.REQUEST_CODE_IMPORT_SETTINGS
                    || requestCode == StockfishNative.REQUEST_CODE_IMPORT_PGN)) {
                try {
                    webView.evaluateJavascript("try{if(typeof onImportCancelled==='function')onImportCancelled('"
                            + (requestCode == StockfishNative.REQUEST_CODE_IMPORT_SETTINGS ? "settings" : "pgn")
                            + "');}catch(e){}", null);
                } catch (Throwable ignored) {}
            }
            return;
        }
        // v1.2.3 round-44 (B4): engine bridge missing — notify JS so the
        //   file-picker UI doesn't hang silently.
        if (stockfishEngine == null) {
            if (webView != null) {
                try {
                    webView.evaluateJavascript("try{if(typeof onFilePickerError==='function')onFilePickerError('engine_unavailable');}catch(e){}", null);
                } catch (Throwable ignored) {}
            }
            return;
        }
        // v1.2.3 round-44 (B8): RESULT_OK with null data is abnormal for SAF
        //   pickers; SafPickerHelper silently returns on null (that file is out
        //   of scope this wave), so surface the error to JS here at the
        //   forwarding layer instead of dropping it.
        if (data == null) {
            if (webView != null) {
                try {
                    webView.evaluateJavascript("try{if(typeof onFilePickerError==='function')onFilePickerError('no_data');}catch(e){}", null);
                } catch (Throwable ignored) {}
            }
            return;
        }
        try {
            if (requestCode == StockfishNative.REQUEST_CODE_IMPORT_SETTINGS) {
                stockfishEngine.handleFilePickerResult(data);
            } else if (requestCode == StockfishNative.REQUEST_CODE_EXPORT_SETTINGS
                    || requestCode == StockfishNative.REQUEST_CODE_EXPORT_PGN) {
                stockfishEngine.handleExportFilePickerResult(data);
            } else if (requestCode == StockfishNative.REQUEST_CODE_IMPORT_PGN) {
                stockfishEngine.handlePGNFilePickerResult(data);
            }
        } catch (Exception e) {
            Log.e(TAG, "onActivityResult failed for request " + requestCode, e);
        }
    }

    public WebView getWebView() {
        return webView;
    }

    // v1.2.3 round-46 (PR53 CR#20): called by ChessWebViewClient just before
    //   it destroys a render-crashed WebView, so this Activity's `webView`
    //   field never keeps referencing a destroyed instance — reusing a
    //   destroyed WebView violates the WebView API contract and can crash.
    void clearWebViewIfMatches(WebView destroyed) {
        if (webView == destroyed) {
            webView = null;
        }
    }

    // ========================================================================
    // v1.0.5 Round-6 Rev49: Sensor-based board anti-shake (OIS-style).
    // ========================================================================
    //
    // The user long-presses any board square to toggle stabilization on/off.
    // The JS-side long-press handler (in ui.js) calls AndroidBridge.toggleStabilization(),
    // which dispatches to toggleStabilization() below.
    //
    // When ON: registers TYPE_LINEAR_ACCELERATION (gravity already removed by
    // OS) and integrates its readings to compute an inverse board displacement.
    // The board's .bwrap element gets a CSS transform that counter-shifts the
    // board in real time, so it appears "locked" to the world frame — mimicking
    // camera optical image stabilization (translation only).
    //
    // When OFF: unregisters the sensor and resets the board to center.
    //
    // Toast notifications (zh/en) are shown on toggle, using the current
    // language preference (read from SharedPreferences "RegaliaEngine" → "lang").
    //
    // Lifecycle: onPause stops stabilization (battery saving); onResume
    // restarts it IF it was enabled before pause. onDestroy stops it.

    /**
     * Toggle the board anti-shake stabilization on/off.
     * Called from the JS long-press handler via AndroidBridge.toggleStabilization().
     * Shows a Toast in the current language (zh/en).
     */
    public void toggleStabilization() {
        // v1.2.3 round-31 (PR52 CodeRabbit stability): serialize against
        //   onDestroy() to prevent the race where the JS binder thread is
        //   mid-toggle (just created a new StabilizationHelper, about to
        //   start()) while the main thread enters onDestroy() and nulls
        //   out the field. Without this lock, the Binder thread would
        //   call start() on a helper whose owner reference was just nulled,
        //   leaking sensors that onDestroy() thought it had stopped.
        //   The lock is fine-grained (_stabilizationLock, not `this`) so
        //   unrelated main-thread entry points (onResume, onPause) aren't
        //   blocked by a long sensor unregister. isDestroyed is checked
        //   inside the lock to short-circuit post-destroy toggles.
        synchronized (_stabilizationLock) {
            if (isDestroyed) {
                // Activity is being destroyed — drop the toggle silently.
                Log.i(TAG, "toggleStabilization ignored — Activity destroyed");
                return;
            }
            if (stabilizationEnabled) {
                // Turn OFF
                if (stabilizationHelper != null) {
                    try { stabilizationHelper.stop(); } catch (Exception e) { Log.w(TAG, "stab stop failed", e); }
                }
                stabilizationEnabled = false;
                showToastLocalized("stabilization_off");
            } else {
                // Turn ON
                if (stabilizationHelper == null && webView != null) {
                    try {
                        stabilizationHelper = new StabilizationHelper(this, webView);
                    } catch (Exception e) {
                        Log.e(TAG, "StabilizationHelper creation failed", e);
                        showToastLocalized("stabilization_unavailable");
                        return;
                    }
                }
                if (stabilizationHelper != null) {
                    boolean ok = false;
                    try { ok = stabilizationHelper.start(); } catch (Exception e) { Log.e(TAG, "stab start failed", e); }
                    if (ok) {
                        stabilizationEnabled = true;
                        showToastLocalized("stabilization_on");
                    } else {
                        showToastLocalized("stabilization_unavailable");
                    }
                }
            }
        }
    }

    /**
     * Show a Toast in the current language (zh/en).
     * @param key one of: "stabilization_on", "stabilization_off", "stabilization_unavailable"
     */
    private void showToastLocalized(String key) {
        // Read language preference (same prefs as StockfishNative.saveLangPref)
        String lang = "zh"; // default
        try {
            android.content.SharedPreferences prefs = getSharedPreferences("RegaliaEngine", MODE_PRIVATE);
            String saved = prefs.getString("lang", null);
            if (saved != null) lang = saved;
            else {
                // Auto-detect from system locale
                // v1.0.8 PHASE 30: use getLocales() on API 24+ (Configuration.locale is deprecated)
                java.util.Locale sys;
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    android.content.res.Configuration cfg = getResources().getConfiguration();
                    sys = (cfg.getLocales() == null || cfg.getLocales().isEmpty())
                            ? java.util.Locale.getDefault() : cfg.getLocales().get(0);
                } else {
                    sys = getResources().getConfiguration().locale;
                }
                if (sys != null && sys.getLanguage() != null && sys.getLanguage().startsWith("en")) lang = "en";
            }
        } catch (Throwable e) {
            Log.w(TAG, "showToastLocalized: lang read failed, defaulting to zh", e);
        }
        String msg;
        if ("stabilization_on".equals(key)) {
            msg = "en".equals(lang) ? "Board stabilization ON" : "棋盘防抖已开启";
        } else if ("stabilization_off".equals(key)) {
            msg = "en".equals(lang) ? "Board stabilization OFF" : "棋盘防抖已关闭";
        } else if ("stabilization_unavailable".equals(key)) {
            msg = "en".equals(lang) ? "Sensors unavailable — stabilization disabled"
                                     : "传感器不可用 — 防抖已禁用";
        } else {
            msg = key;
        }
        try {
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    try {
                        android.widget.Toast.makeText(MainActivity.this, msg, android.widget.Toast.LENGTH_LONG).show();
                    } catch (Throwable e) {
                        Log.w(TAG, "Toast show failed", e);
                    }
                }
            });
        } catch (Throwable e) {
            Log.w(TAG, "showToastLocalized post failed", e);
        }
    }
}
